spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    schema: classpath:h2/schema.sql

  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC

subway:
  file-path:
    monthly: src/main/resources/data/monthly/